env:
  global:
    TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER

matrix:
  include:
  - env:
    - NAME=web-build
    services:
    - docker
    dist: xenial
    language: cpp
    before_install:
    - openssl aes-256-cbc -K $encrypted_a79bb47bd049_key -iv $encrypted_a79bb47bd049_iv -in store.tar.enc -out store.tar -d
    - tar xvf store.tar
    install:
    - docker build -t webpages -f Dockerfile --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER" .
    script:
    - docker run -a stdout -t webpages git rev-parse HEAD~1 
    - echo $TRAVIS_JOB_NUMBER
